[package]
name = "oca-sdk-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
oca-rs = { version = "0.6.3" }
oca-ast-semantics = { version = "0.6.3" }
oca-bundle-semantics = { version = "0.6.3", features = ["format_overlay"] }
transformation-file = { version = "0.6.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
